package gestionGimnasio.GUI;

import gestionGimnasio.Ejercicio;
import gestionGimnasio.DatosRep;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

public class FrmEjercicios extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(FrmEjercicios.class.getName());

    private int filaSeleccionada = -1;

    public FrmEjercicios() {
        initComponents();

        setLocationRelativeTo(null);
        configurarTabla();
        cargarDificultades();
        cargarTabla();
    }

    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{
                    "Identificacion",
                    "Nombre",
                    "Dificultad",
                    "Descripcion"
                }, 0
        ) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };

        tblEjercicios.setModel(modelo);
        tblEjercicios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void cargarTabla() {
        DefaultTableModel modelo
                = (DefaultTableModel) tblEjercicios.getModel();

        modelo.setRowCount(0);

        for (Ejercicio ejercicio : DatosRep.EJERCICIOS.obtenerTodos()) {
            modelo.addRow(new Object[]{
                ejercicio.getIdentificacion(),
                ejercicio.getNombre(),
                ejercicio.getDificultad(),
                ejercicio.getDescripcion()
            }
            );
        }
    }

    private void cargarDificultades() {
        cmbDificultad.removeAllItems();
        cmbDificultad.addItem("Principiante");
        cmbDificultad.addItem("Intermedio");
        cmbDificultad.addItem("Avanzado");
    }

    private boolean validarCampos() {

        if (txtIdentificacion.getText().trim().isEmpty()) {
            JOptionPane.showConfirmDialog(
                    this,
                    "Debe ingresar el Identificacion"
            );

            txtIdentificacion.requestFocus();
            return false;
        }

        if (txtNombre.getText().trim().isEmpty()) {
            JOptionPane.showConfirmDialog(
                    this,
                    "Debe ingresar el nombre"
            );

            txtNombre.requestFocus();
            return false;
        }

        if (cmbDificultad.getSelectedIndex() < 0) {
            JOptionPane.showConfirmDialog(
                    this,
                    "Seleccione la dificultad.",
                    "Dato requerido",
                    JOptionPane.WARNING_MESSAGE
            );

            cmbDificultad.requestFocus();
            return false;
        }

        if (txtDescripcion.getText().trim().isEmpty()) {
            JOptionPane.showConfirmDialog(
                    this,
                    "Debe ingresar la Descripcion"
            );

            txtDescripcion.requestFocus();
            return false;
        }

        return true;
    }

    private void limpiarFormulario() {

        txtIdentificacion.setText("");
        txtNombre.setText("");

        if (cmbDificultad.getItemCount() > 0) {
            cmbDificultad.setSelectedIndex(0);
        }

        txtDescripcion.setText("");

        tblEjercicios.clearSelection();

        filaSeleccionada = -1;

        txtIdentificacion.requestFocus();
    }

    private Ejercicio crearEjercicioDesdeFormulario() {
        return new Ejercicio(
                txtIdentificacion.getText().trim(),
                txtNombre.getText().trim(),
                cmbDificultad.getSelectedItem().toString(),
                txtDescripcion.getText().trim()
        );
    }

    private void cargarEjercicioSeleccionado() {

        filaSeleccionada = tblEjercicios.getSelectedRow();

        if (filaSeleccionada < 0) {
            return;
        }

        Ejercicio ejercicio
                = DatosRep.EJERCICIOS.obtener(filaSeleccionada);

        if (ejercicio == null) {
            return;
        }

        txtIdentificacion.setText(
                ejercicio.getIdentificacion()
        );

        txtNombre.setText(
                ejercicio.getNombre()
        );

        cmbDificultad.setSelectedItem(
                ejercicio.getDificultad()
        );

        txtDescripcion.setText(
                ejercicio.getDescripcion()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDificultad = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cmbDificultad = new javax.swing.JComboBox<>();
        txtDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEjercicios = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Ejercicios");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setText("Gestion de Ejercicios");

        lblCodigo.setText("Codigo:");

        lblNombre.setText("Nombre:");

        lblDificultad.setText("Dificultad:");

        lblDescripcion.setText("Descripcion:");

        cmbDificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principiante", "Intermedio", "Avanzado" }));

        tblEjercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Dificultad", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEjercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEjerciciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEjercicios);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDificultad)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCodigo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNombre)
                                    .addGap(32, 32, 32)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDescripcion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(275, 275, 275))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDificultad)
                    .addComponent(cmbDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCerrar))
                .addGap(25, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tblEjerciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEjerciciosMouseClicked
        cargarEjercicioSeleccionado();
    }//GEN-LAST:event_tblEjerciciosMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!validarCampos()) {
            return;
        }

        Ejercicio ejercicio
                = crearEjercicioDesdeFormulario();

        DatosRep.EJERCICIOS.agregar(ejercicio);

        cargarTabla();
        limpiarFormulario();

        JOptionPane.showMessageDialog(
                this,
                "Ejercicio registrado correctamente"
        );
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un ejercicio dentro de la tabla"
            );

            return;
        }

        if (!validarCampos()) {
            return;
        }

        Ejercicio ejercicioAct
                = crearEjercicioDesdeFormulario();

        boolean actualizado
                = DatosRep.EJERCICIOS.actualizar(
                        filaSeleccionada,
                        ejercicioAct
                );

        if (actualizado) {

            cargarTabla();
            limpiarFormulario();

            JOptionPane.showMessageDialog(
                    this,
                    "Ejercicio actualizado correctamente"
            );

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo actualizar el Ejercicio"
            );
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (filaSeleccionada < 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un Ejercicio dentro de la tabla"
            );

            return;
        }

        Ejercicio ejercicio
                = DatosRep.EJERCICIOS.obtener(
                        filaSeleccionada
                );

        if (ejercicio == null) {
            return;
        }

        int respuesta
                = JOptionPane.showConfirmDialog(
                        this,
                        "Desea eliminar el ejercicio "
                        + ejercicio.getNombre() + "?",
                        "Confirmar eliminacion",
                        JOptionPane.YES_NO_OPTION
                );

        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        boolean eliminado
                = DatosRep.EJERCICIOS.eliminar(
                        filaSeleccionada
                );

        if (eliminado) {

            cargarTabla();
            limpiarFormulario();

            JOptionPane.showMessageDialog(
                    this,
                    "Ejercicio eliminado correctamente"
            );

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo eliminar el Ejercicio"
            );
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    public static void main(String args[]) {

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(
                            info.getClassName()
                    );

                    break;
                }
            }

        } catch (ReflectiveOperationException
                | javax.swing.UnsupportedLookAndFeelException ex) {

            logger.log(
                    java.util.logging.Level.SEVERE,
                    null,
                    ex
            );
        }

        java.awt.EventQueue.invokeLater(
                () -> new FrmEjercicios().setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbDificultad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDificultad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblEjercicios;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
