
package gestionGimnasio.GUI;

import javax.swing.JOptionPane;
import gestionGimnasio.Utilidades;
import gestionGimnasio.Usuario;
import gestionGimnasio.DatosRep;
public class FrmLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    /**
     * Creates new form Login
     */
    public FrmLogin() 
    {
        initComponents();
        
        setLocationRelativeTo(null);

        getRootPane().setDefaultButton(btnIngresar);
         
        
        
        //Usuario admin para entrar al sistema como administrador
        Usuario u = new Usuario("admin","1234","Admin","Activo");
        boolean uActivo=false;
        for(Usuario uu: DatosRep.USUARIOS.obtenerTodos())
        {
            if(u.getNombreUsuario().equals(uu.getNombreUsuario()) && uu.getRol().equals("Admin"))
            {
                uActivo=true;
            }
        }
        if(!uActivo) {DatosRep.USUARIOS.agregar(u);}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtContrasena = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        btnCrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana_Login");
        setLocation(new java.awt.Point(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(405, 500));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Inicio de sesion Gimnasio");

        lblUsuario.setText("Usuario:");

        lblContraseña.setText("Contraseña:");

        btnCrearCuenta.setText("Crear Cuenta");
        btnCrearCuenta.addActionListener(this::btnCrearCuentaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnCrearCuenta)
                .addGap(38, 38, 38)
                .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblContraseña))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addContainerGap(55, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnCrearCuenta))
                .addGap(82, 82, 82))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUsuario))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblContraseña))
                    .addContainerGap(328, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private boolean validarCampos()
    {
        if (txtUsuario.getText().trim().isEmpty()) {
            JOptionPane.showConfirmDialog(this, "Debe ingresar la Identificacion");
            txtUsuario.requestFocus();
            return false;
        } 
        if (txtContrasena.getPassword().length == 0) {
            JOptionPane.showConfirmDialog(this, "Debe ingresar la contraseña");
            txtContrasena.requestFocus();
            return false;
        } 
        
        for (Usuario usuario : DatosRep.USUARIOS.obtenerTodos()) 
        {
           if(usuario.getNombreUsuario().equals(txtUsuario.getText().trim()))
           {
               JOptionPane.showMessageDialog(this, "Usuario en uso","Intente uno nuevo", JOptionPane.ERROR_MESSAGE);
               return false;
           }
        }
        return true;
    }
   
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       
        String usuario = txtUsuario.getText().trim();
        String contrasena = new String(txtContrasena.getPassword());
        Usuario u = new Usuario(usuario, contrasena);
        
        if(Utilidades.ValidarAcceso(u)) 
        {
            FrmPrincipal ventanaPrincipal = new FrmPrincipal(u);
            ventanaPrincipal.setVisible(true);
            dispose();
        } else {

            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Acceso denegado", JOptionPane.ERROR_MESSAGE);

            txtContrasena.setText("");
            txtContrasena.requestFocus();
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    
    private Usuario crearUsuarioDesdeFormulario()
   {
       //String identificacion, String nombreCompleto, String telefono, String correo, String especialidad, String estado
       
       
        return new Usuario
        (
            txtUsuario.getText().trim(),
            new String(txtContrasena.getPassword())
         );
       
       
   }
    
    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        if(!validarCampos()){
            return;
        }
        
        Usuario usuario = crearUsuarioDesdeFormulario();
        
        DatosRep.USUARIOS.agregar(usuario);
        txtContrasena.setText("");
        
        JOptionPane.showMessageDialog(this, "Usuario registrado correctamente");
    }//GEN-LAST:event_btnCrearCuentaActionPerformed
 
    
    
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
