
package gestionGimnasio.GUI;

import javax.swing.JOptionPane;

import gestionGimnasio.DatosRep;
import gestionGimnasio.Usuario;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

public class FrmUsuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmUsuarios.class.getName());
    private int filaSeleccionada = -1;
    
    


    public FrmUsuarios() 
    {
        initComponents();
        
        configurarTabla();
        limpiarFormulario();
        cargarEstados();
        cargarRol();
        cargarTabla();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblContrasena = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        txtContrasena = new javax.swing.JTextField();
        cmbRol = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GestionGimnasio - Gestión de Usuarios");
        setSize(new java.awt.Dimension(850, 650));

        lblContrasena.setText("Contraseña");

        lblRol.setText("Rol");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setText("Administracion de Usuarios");

        lblNombreUsuario.setText("Nombre de Usuario");

        txtNombreUsuario.addActionListener(this::txtNombreUsuarioActionPerformed);

        lblEstado.setText("Estado");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtContrasena.addActionListener(this::txtContrasenaActionPerformed);

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(75, 75, 75)
                        .addComponent(btnGuardar)
                        .addGap(90, 90, 90)
                        .addComponent(btnActualizar)
                        .addGap(92, 92, 92)
                        .addComponent(btnEliminar)
                        .addGap(64, 64, 64)
                        .addComponent(btnCerrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTitulo)
                                .addGap(167, 167, 167))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombreUsuario))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreUsuario)
                                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtContrasena)
                                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitulo)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUsuario)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRol)
                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblContrasena)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEstado)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCerrar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTabla() {

        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{
                    "Nombre de Usuario",
                    "Estado",
                    "Rol",
                    "Contraseña"
                },
                0
        ) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };

        tblUsuarios.setModel(modelo);
        tblUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblUsuarios.getTableHeader().setReorderingAllowed(false);

        tblUsuarios.getColumnModel().getColumn(0).setPreferredWidth(150);
        tblUsuarios.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblUsuarios.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblUsuarios.getColumnModel().getColumn(3).setPreferredWidth(150);

    }
    
    
     private void limpiarFormulario() {

        txtNombreUsuario.setText("");
        txtContrasena.setText("");
        if (cmbEstado.getItemCount() > 0) {
            cmbEstado.setSelectedIndex(0);

        }
        if (cmbRol.getItemCount() > 0) {
            cmbRol.setSelectedIndex(0);

        }

        

        tblUsuarios.clearSelection();
        filaSeleccionada = -1;
    }
    
    private void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();
        modelo.setRowCount(0);
        for (Usuario usuario : DatosRep.USUARIOS.obtenerTodos()) {
            modelo.addRow(
                    new Object[]{
                        usuario.getNombreUsuario(),
                        usuario.getEstado(),
                        usuario.getRol(),
                        usuario.getContrasena()

                    }
            );
        }
    }
    
    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private boolean validarCampos() {

        if (txtNombreUsuario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debe ingresar el nombre de usuario.",
                    "Dato requerido",
                    JOptionPane.WARNING_MESSAGE
            );
            txtNombreUsuario.requestFocus();
            return false;
        }

        if (txtContrasena.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Debe ingresar la contrasena.",
                    "Dato requerido",
                    JOptionPane.WARNING_MESSAGE
            );

            txtContrasena.requestFocus();
            return false;
        }

        if (cmbEstado.getSelectedIndex() < 0) {
            JOptionPane.showConfirmDialog(this, "Seleccione un estado.", "Dato requerido", JOptionPane.WARNING_MESSAGE);
            
            cmbEstado.requestFocus();
            return false;
        }
        if (cmbRol.getSelectedIndex() < 0) {
            JOptionPane.showConfirmDialog(this, "Seleccione un rol.", "Dato requerido", JOptionPane.WARNING_MESSAGE);
            
            cmbRol.requestFocus();
            return false;
        }

        return true;
    }
    
    
    private void cargarUsuarioSeleccionado() {
        int filaVista = tblUsuarios.getSelectedRow();
        if (filaVista < 0) {
            return;
        }

        filaSeleccionada = tblUsuarios.convertRowIndexToModel(filaVista);

        Usuario usuario = DatosRep.USUARIOS.obtener(filaSeleccionada);

        if (usuario == null) {
            return;
        }
        
        
        txtNombreUsuario.setText(usuario.getNombreUsuario());
        txtContrasena.setText(usuario.getContrasena());
        cmbEstado.setSelectedItem(usuario.getEstado());
        cmbRol.setSelectedItem(usuario.getRol());
    }
    
    private void cargarEstados() {
        cmbEstado.removeAllItems();
        cmbEstado.addItem("Activo");
        cmbEstado.addItem("Inactivo");
    }
    
    private void cargarRol() 
    {
        cmbRol.removeAllItems();
        cmbRol.addItem("Admin");
        cmbRol.addItem("Operario");
    }
    
    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    
    private Usuario crearUsuarioDesdeFormulario()
    {
        
        return new Usuario(
                txtNombreUsuario.getText().trim(),
                txtContrasena.getText().trim(),
                cmbRol.getSelectedItem().toString(),
                cmbEstado.getSelectedItem().toString()
                
                
        );
    }
    
    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked

        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(
                this,
                "Seleccione un Usuario en la tabla.",
                "Usuario no seleccionado",
                JOptionPane.WARNING_MESSAGE
            );

            return;

        }

        if (!validarCampos()) {
            return;
        }

        Usuario usuarioAct = crearUsuarioDesdeFormulario();

        boolean actualizado = DatosRep.USUARIOS.actualizar(
            filaSeleccionada,
            usuarioAct
        );

        if (actualizado) {
            cargarTabla();
            usuarioAct.mostrarResumen();
            limpiarFormulario();
            JOptionPane.showMessageDialog(
                this,
                "Usuario actualizado correctamente.",
                "Actualización realizada",
                JOptionPane.INFORMATION_MESSAGE
                
            );

        } else {

            JOptionPane.showMessageDialog(
                this,
                "No se pudo actualizar el usuario.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );

        }
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if (filaSeleccionada < 0) {

            JOptionPane.showMessageDialog(
                this,
                "Seleccione un usuario en la tabla.",
                "Usuario no seleccionada",
                JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        Usuario usuario = DatosRep.USUARIOS.obtener(filaSeleccionada);

        if (usuario == null) {
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(
            this,
            "Desea eliminar el usuario "
            + usuario.getNombreUsuario() + " - " + usuario.getContrasena()
            + "?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        boolean eliminado = DatosRep.USUARIOS.eliminar(filaSeleccionada);

        if (eliminado) {

            cargarTabla();
            limpiarFormulario();

            JOptionPane.showMessageDialog(
                this,
                "Usuario eliminada correctamente.",
                "Eliminación realizada",
                JOptionPane.INFORMATION_MESSAGE
            );

        } else {

            JOptionPane.showMessageDialog(
                this,
                "No se pudo eliminar el usuario.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );

        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        dispose();
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked

        if (!validarCampos()) {
            return;
        }

        Usuario usuario = crearUsuarioDesdeFormulario();
        DatosRep.USUARIOS.agregar(usuario);

        cargarTabla();
        limpiarFormulario();

        JOptionPane.showMessageDialog(
            this,
            "Usuario registrado correctamente.",
            "Registro realizado",
            JOptionPane.INFORMATION_MESSAGE
        );

    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        cargarUsuarioSeleccionado();
    }//GEN-LAST:event_tblUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
